SQLALCHEMY_DATABASE_URI = 'postgresql://postgres@localhost/roadwork_api'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True

ROADWORKAPI_IMAGE_MAX_DIMENSIONS = (1000, 1000)
ROADWORKAPI_IMAGE_STORAGE = 'tmp'

ROADWORKAPI_MAX_ISSUES_PER_PAGE = 50
ROADWORKAPI_MAX_TAGS_PER_PAGE = 500
