"""Initial database structure

Revision ID: 84237906f80d
Revises: None
Create Date: 2017-06-25 18:56:32.676949

"""

# revision identifiers, used by Alembic.
revision = '84237906f80d'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_key')
    )
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('streetview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('image_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'image_id')
    )
    op.create_table('issue_version',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('coordinates_id', sa.Integer(), nullable=False),
    sa.Column('description_id', sa.Integer(), nullable=True),
    sa.Column('tag_group_id', sa.Integer(), nullable=True),
    sa.Column('image_group_id', sa.Integer(), nullable=True),
    sa.Column('streetview_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinates_id'], ['coordinates.id'], ),
    sa.ForeignKeyConstraint(['description_id'], ['description.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.ForeignKeyConstraint(['streetview_id'], ['streetview.id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'version')
    )
    op.create_table('tag_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'tag_id')
    )

    op.execute(CreateSequence(Sequence('tag_group_id_seq')))
    op.execute(CreateSequence(Sequence('image_group_id_seq')))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_group')
    op.drop_table('issue_version')
    op.drop_table('image_group')
    op.drop_table('tag')
    op.drop_table('streetview')
    op.drop_table('state')
    op.drop_table('issue')
    op.drop_table('image')
    op.drop_table('description')
    op.drop_table('coordinates')

    op.execute(DropSequence(Sequence('tag_group_id_seq')))
    op.execute(DropSequence(Sequence('image_group_id_seq')))
    ### end Alembic commands ###
